def hq_phase(round_number, p_one, p_two):
    print("hq:", round_number)
    p_one.ready_all_in_play()
    p_two.ready_all_in_play()
    p_one.add_resources(4)
    p_two.add_resources(4)
    p_one.draw_card()
    p_one.draw_card()
    p_two.draw_card()
    p_two.draw_card()
    print(p_one.get_resources())
    print(p_two.get_resources())
